### ISSUE TITLE
Hi, is this framework still being maintained and updated?

### ISSUE THREAD

**Issue by StarSkyK** [InvadingOctopus/octopuskit#15]
Hi, is this framework still being maintained and updated?

**Comment by ShinryakuTako** [comment]
Hey, sorry for the late reply, I'm still trying to do a major overhaul of this, to make it deeply integrated with SwiftUI and maybe even add a visual editor :)

**Comment by StarSkyK** [comment]
> Hey, sorry for the late reply, I'm still trying to do a major overhaul of this, to make it deeply integrated with SwiftUI and maybe even add a visual editor :)

WOW, exciting! For spritekit there is a great need for such a thing. Can you roughly reveal when the next big release will be?

**Comment by ShinryakuTako** [comment]
No idea. I work on it bit by bit in my free time and I'm not even sure if it's really possible yet (´・ω・｀)

**Comment by iusn** [comment]
> Hey, sorry for the late reply, I'm still trying to do a major overhaul of this, to make it deeply integrated with SwiftUI and maybe even add a live editor :)

I would recommend that we stay away from switui for the next few years because swiftui changes every year and has its own set of bugs and performance issues. octopuskit's first priority is to make it available, accessible, and engaging

**Comment by MadeByDouglas** [comment]
This library looks really cool, hope you continue to work on it. 

Just to share my thoughts, SwiftUI has gotten stable with iOS 16+ and its great you are supporting it, Its the future, even if its had a lot of growing pains. I wouldn't worry about the visual editor though, that seems like a lot of work for one person and the audience for this library is going to be Swift fans who code right?

I am wondering, is there anyway to integrate this with Godot? This library is great because it uses Metal and follows Apple's best practices, Godot is great because its multi-platform and has a lot of support, however its really not a good engine for Apple devices since it still uses OpenGL. I know Godot can support custom languages which could work with Swift, would that be a door for this library to integrate?  Maybe it doesn't make sense, but what would be cool is to somehow just write Swift and have a great native Apple game while also having a great multiplatform game via Godot.

**Comment by theSalted** [comment]
> This library looks really cool, hope you continue to work on it.
> 
> Just to share my thoughts, SwiftUI has gotten stable with iOS 16+ and its great you are supporting it, Its the future, even if its had a lot of growing pains. I wouldn't worry about the visual editor though, that seems like a lot of work for one person and the audience for this library is going to be Swift fans who code right?
> 
> I am wondering, is there anyway to integrate this with Godot? This library is great because it uses Metal and follows Apple's best practices, Godot is great because its multi-platform and has a lot of support, however its really not a good engine for Apple devices since it still uses OpenGL. I know Godot can support custom languages which could work with Swift, would that be a door for this library to integrate? Maybe it doesn't make sense, but what would be cool is to somehow just write Swift and have a great native Apple game while also having a great multiplatform game via Godot.

The project you are describing here already exists:-), check out (SwiftGodot)[https://github.com/migueldeicaza/SwiftGodot]

**Comment by MadeByDouglas** [comment]
Thats super cool! However, as just a wrapper to Godot, it still doesn't use Metal under the hood then right? Thats the issue with Godot right now whereas using SpriteKit / SceneKit is better in that way.
And the idea here to use swiftUI for interface is cool as well, of course that couldn't be implemented in Godot which needs to be cross platform.

**Comment by theSalted** [comment]
> Thats super cool! However, as just a plugin to Godot, it still doesn't use Metal under the hood then right? Thats the issue with Godot right now whereas using SpriteKit / SceneKit is better in that way. And the idea here to use swiftUI for interface is cool as well, of course that couldn't be implemented in Godot which needs to be cross platform.

Oh, so you meant integrate this with Godot. I don't think that's possible given OctupusKit built on top of SpriteKit - a proprietary Apple framework. 
As for Godot supporting Metal, their official documentation says "a native Metal driver is planned in the future for better performance and compatibility".

**Comment by MadeByDouglas** [comment]
yeah that makes sense. I guess it would be cool to share some common logic in Godot, and have some specific code for apple devices in OctopusKit. But maybe it doesn't make sense, I'm just thinking out loud. Godot supporting Metal and Swift is probably the most practical way forward, but I like what this library is trying to achieve with first party tools for apple devices.

**Comment by theSalted** [comment]
> yeah that makes sense. I guess it would be cool to share some common logic in Godot, and have some specific code for apple devices in OctopusKit. But maybe it doesn't make sense, I'm just thinking out loud. Godot supporting Metal and Swift is probably the most practical way forward, but I like what this library is trying to achieve with first party tools for apple devices.

Yeah I like OctopusKit because it makes working with Apple's own frameworks easier. Before Apple added SpriteView to SwiftUI, OctopusKit was the best way for me to use SpriteKit in SwiftUI projects. Also, it's great for using GameplayKit with SpriteKit. SpriteKit's own integration with GameplayKit was designed for the GUI editor, when you do it programmatically there are lots of caveats. 

I think Swift is a good language for games because it's friendly syntax; deterministic performance thanks to ARC; It's less also rigid than languages like Rust, making it fast to prototype. I like SwiftGodot for the same reasons.

Ultimately, I wish Apple would open source SpriteKit and SceneKit. For many developers lack of cross-platform support is a deal breaker. Open source SpriteKit and SceneKit would at least enable the possibility of porting.

**Comment by ShinryakuTako** [comment]
Ummm so I may have to admit that the OctopusKit project might as well be considered abandoned.. 😔

I have moved on to Godot, and loving it, although I do miss Swift (I prefer working inside the editor with GDScript).

Maybe someday when I can chill indefinitely in life I might overhaul this project from scratch as a node-based engine like Godot, but that would be reinventing too many wheels, just to be able to use Swift in a native Mac game engine editor.

**Comment by ShinryakuTako** [comment]
In case anyone is still looking at this project, I have been working on a new components-based framework for Godot: https://github.com/InvadingOctopus/comedot

I don't know if the people who were interested in the fate of OctopusKit will see this message, but if you're still looking for a good engine to make games in, give Godot a try! I miss Swift but everything has been so much easier in Godot and it's a blast!

**Comment by MadeByDouglas** [comment]
Makes sense, good luck with your games!

**Comment by davidreedme** [comment]
Cool. Thanks for the update/pointer. Good hunting.
